/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Engine__factory } from "./Engine__factory";
export { Motorbike__factory } from "./Motorbike__factory";
