/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as delegationSol from "./Delegation.sol";
export type { delegationSol };
import type * as elevatorSol from "./Elevator.sol";
export type { elevatorSol };
export type { CoinFlip } from "./CoinFlip";
export type { CoinFlipAttack } from "./CoinFlipAttack";
export type { ElevatorAttack } from "./ElevatorAttack";
export type { Fallback } from "./Fallback";
export type { Fallout } from "./Fallout";
export type { ForceAttack } from "./ForceAttack";
export type { GatekeeperOne } from "./GatekeeperOne";
export type { GatekeeperOneAttack } from "./GatekeeperOneAttack";
export type { GatekeeperTwo } from "./GatekeeperTwo";
export type { GatekeeperTwoAttack } from "./GatekeeperTwoAttack";
export type { King } from "./King";
export type { KingAttack } from "./KingAttack";
export type { NaughtCoin } from "./NaughtCoin";
export type { Privacy } from "./Privacy";
export type { Reentrance } from "./Reentrance";
export type { ReentranceAttack } from "./ReentranceAttack";
export type { Telephone } from "./Telephone";
export type { TelephoneAttack } from "./TelephoneAttack";
export type { Token } from "./Token";
export type { Vault } from "./Vault";
