/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Recovery__factory } from "./Recovery__factory";
export { SimpleToken__factory } from "./SimpleToken__factory";
