/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDetectionBot,
  IDetectionBotInterface,
} from "../../../contracts/DoubleEPBot.sol/IDetectionBot";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "msgData",
        type: "bytes",
      },
    ],
    name: "handleTransaction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDetectionBot__factory {
  static readonly abi = _abi;
  static createInterface(): IDetectionBotInterface {
    return new utils.Interface(_abi) as IDetectionBotInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDetectionBot {
    return new Contract(address, _abi, signerOrProvider) as IDetectionBot;
  }
}
