/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IForta,
  IFortaInterface,
} from "../../../contracts/DoubleEPBot.sol/IForta";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "msgData",
        type: "bytes",
      },
    ],
    name: "notify",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "raiseAlert",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "detectionBotAddress",
        type: "address",
      },
    ],
    name: "setDetectionBot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IForta__factory {
  static readonly abi = _abi;
  static createInterface(): IFortaInterface {
    return new utils.Interface(_abi) as IFortaInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IForta {
    return new Contract(address, _abi, signerOrProvider) as IForta;
  }
}
