/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DetectionBot__factory } from "./DetectionBot__factory";
export { IDetectionBot__factory } from "./IDetectionBot__factory";
export { IForta__factory } from "./IForta__factory";
