/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { GatekeeperOne, GatekeeperOneInterface } from "../GatekeeperOne";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes8",
        name: "_gateKey",
        type: "bytes8",
      },
    ],
    name: "enter",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "entrant",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103b3806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633370204e1461003b5780639db31d771461008e575b600080fd5b61007a6004803603602081101561005157600080fd5b50357fffffffffffffffff000000000000000000000000000000000000000000000000166100bf565b604080519115158252519081900360200190f35b6100966101fc565b6040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f35b6000333214156100ce57600080fd5b6100db611fff5a90610218565b156100e557600080fd5b818060c01c61ffff168160c01c63ffffffff16146101345760405162461bcd60e51b81526004018080602001828103825260298152602001806103016029913960400191505060405180910390fd5b60c081901c63ffffffff8116141561017d5760405162461bcd60e51b815260040180806020018281038252602981526020018061032a6029913960400191505060405180910390fd5b3261ffff168160c01c63ffffffff16146101c85760405162461bcd60e51b815260040180806020018281038252602b815260200180610353602b913960400191505060405180910390fd5b600080547fffffffffffffffffffffffff000000000000000000000000000000000000000016321790556001915050919050565b60005473ffffffffffffffffffffffffffffffffffffffff1681565b600061025a83836040518060400160405280601881526020017f536166654d6174683a206d6f64756c6f206279207a65726f0000000000000000815250610261565b9392505050565b600081836102ed5760405162461bcd60e51b81526004018080602001828103825283818151815260200191508051906020019080838360005b838110156102b257818101518382015260200161029a565b50505050905090810190601f1680156102df5780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b508284816102f757fe5b0694935050505056fe476174656b65657065724f6e653a20696e76616c6964206761746554687265652070617274206f6e65476174656b65657065724f6e653a20696e76616c69642067617465546872656520706172742074776f476174656b65657065724f6e653a20696e76616c6964206761746554687265652070617274207468726565a2646970667358221220652573b068b3143d4d1b2e957e113a4459cde3382d81cff768f3ebbd92e13e3c64736f6c634300060c0033";

type GatekeeperOneConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GatekeeperOneConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GatekeeperOne__factory extends ContractFactory {
  constructor(...args: GatekeeperOneConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<GatekeeperOne> {
    return super.deploy(overrides || {}) as Promise<GatekeeperOne>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): GatekeeperOne {
    return super.attach(address) as GatekeeperOne;
  }
  override connect(signer: Signer): GatekeeperOne__factory {
    return super.connect(signer) as GatekeeperOne__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GatekeeperOneInterface {
    return new utils.Interface(_abi) as GatekeeperOneInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GatekeeperOne {
    return new Contract(address, _abi, signerOrProvider) as GatekeeperOne;
  }
}
