/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Telephone, TelephoneInterface } from "../Telephone";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "changeOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610134806100326000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80638da5cb5b146037578063a6f9dae1146066575b600080fd5b603d6098565b6040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f35b609660048036036020811015607a57600080fd5b503573ffffffffffffffffffffffffffffffffffffffff1660b4565b005b60005473ffffffffffffffffffffffffffffffffffffffff1681565b32331460fb57600080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff83161790555b5056fea26469706673582212203e50f6d502b68722e6e265fc4f1b957c897e1315dbc65634b2d7259ea11ccc1264736f6c634300060c0033";

type TelephoneConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TelephoneConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Telephone__factory extends ContractFactory {
  constructor(...args: TelephoneConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Telephone> {
    return super.deploy(overrides || {}) as Promise<Telephone>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Telephone {
    return super.attach(address) as Telephone;
  }
  override connect(signer: Signer): Telephone__factory {
    return super.connect(signer) as Telephone__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TelephoneInterface {
    return new utils.Interface(_abi) as TelephoneInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Telephone {
    return new Contract(address, _abi, signerOrProvider) as Telephone;
  }
}
