/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AlienCodex__factory } from "./AlienCodex__factory";
export { Ownable__factory } from "./Ownable__factory";
