/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  GatekeeperTwoAttack,
  GatekeeperTwoAttackInterface,
} from "../../GatekeeperTwoAttack.sol/GatekeeperTwoAttack";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50604051609e380380609e83398181016040526020811015602f57600080fd5b5051600080546001600160a01b039092166001600160a01b0319909216919091179055603f80605f6000396000f3fe6080604052600080fdfea2646970667358221220d393a9cd411a749b077dd05b08b2446d12c7f0ca67e64e8fca907e7174d05e6064736f6c634300060c0033";

type GatekeeperTwoAttackConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GatekeeperTwoAttackConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GatekeeperTwoAttack__factory extends ContractFactory {
  constructor(...args: GatekeeperTwoAttackConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<GatekeeperTwoAttack> {
    return super.deploy(
      _address,
      overrides || {}
    ) as Promise<GatekeeperTwoAttack>;
  }
  override getDeployTransaction(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_address, overrides || {});
  }
  override attach(address: string): GatekeeperTwoAttack {
    return super.attach(address) as GatekeeperTwoAttack;
  }
  override connect(signer: Signer): GatekeeperTwoAttack__factory {
    return super.connect(signer) as GatekeeperTwoAttack__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GatekeeperTwoAttackInterface {
    return new utils.Interface(_abi) as GatekeeperTwoAttackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GatekeeperTwoAttack {
    return new Contract(address, _abi, signerOrProvider) as GatekeeperTwoAttack;
  }
}
