/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  CoinFlipAttack,
  CoinFlipAttackInterface,
} from "../../contracts/CoinFlipAttack";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "attack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052600160ff1b60015534801561001857600080fd5b506040516103443803806103448339818101604052602081101561003b57600080fd5b5051600080546001600160a01b039092166001600160a01b03199092169190911790556102d78061006d6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80639e5faafc14610030575b600080fd5b61003861003a565b005b600061004743600161011a565b6001549040915060009061005c908390610163565b905060008160011461006f576000610072565b60015b905060008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16631d263f67826040518263ffffffff1660e01b8152600401808215158152602001915050602060405180830381600087803b1580156100e957600080fd5b505af11580156100fd573d6000803e3d6000fd5b505050506040513d602081101561011357600080fd5b5050505050565b600061015c83836040518060400160405280601e81526020017f536166654d6174683a207375627472616374696f6e206f766572666c6f7700008152506101a5565b9392505050565b600061015c83836040518060400160405280601a81526020017f536166654d6174683a206469766973696f6e206279207a65726f00000000000081525061023c565b600081848411156102345760405162461bcd60e51b81526004018080602001828103825283818151815260200191508051906020019080838360005b838110156101f95781810151838201526020016101e1565b50505050905090810190601f1680156102265780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b505050900390565b6000818361028b5760405162461bcd60e51b81526020600482018181528351602484015283519092839260449091019190850190808383600083156101f95781810151838201526020016101e1565b50600083858161029757fe5b049594505050505056fea2646970667358221220b223bbec30b495da0db182846db02bea235f50cd08c36418aa58f64e23d5f5ee64736f6c634300060c0033";

type CoinFlipAttackConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CoinFlipAttackConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CoinFlipAttack__factory extends ContractFactory {
  constructor(...args: CoinFlipAttackConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<CoinFlipAttack> {
    return super.deploy(_address, overrides || {}) as Promise<CoinFlipAttack>;
  }
  override getDeployTransaction(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_address, overrides || {});
  }
  override attach(address: string): CoinFlipAttack {
    return super.attach(address) as CoinFlipAttack;
  }
  override connect(signer: Signer): CoinFlipAttack__factory {
    return super.connect(signer) as CoinFlipAttack__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CoinFlipAttackInterface {
    return new utils.Interface(_abi) as CoinFlipAttackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CoinFlipAttack {
    return new Contract(address, _abi, signerOrProvider) as CoinFlipAttack;
  }
}
