/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DetectionBot } from "./DetectionBot";
export type { IDetectionBot } from "./IDetectionBot";
export type { IForta } from "./IForta";
