/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GatekeeperOneAttack } from "./GatekeeperOneAttack";
export type { GatekeeperTwoAttack } from "./GatekeeperTwoAttack";
