/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PuzzleProxy__factory } from "./PuzzleProxy__factory";
export { PuzzleWallet__factory } from "./PuzzleWallet__factory";
